name: Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - master
      - develop
      - pipeline-test
  workflow_dispatch:

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    
    env:
      AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      AZURE_DEVOPS_SOURCE_BRANCH: ${{ vars.AZURE_DEVOPS_SOURCE_BRANCH }}
      AZURE_DEVOPS_PIPELINE_DEFINITION_ID: ${{ vars.AZURE_DEVOPS_PIPELINE_DEFINITION_ID }}
      AZURE_DEVOPS_ORGANIZATION: ${{ vars.AZURE_DEVOPS_ORGANIZATION }}
      AZURE_DEVOPS_PROJECT: ${{ vars.AZURE_DEVOPS_PROJECT }}

  
    
    steps:
    - name: Trigger Azure Devops Pipeline
      shell: bash
      run: |
        echo "Triggering Azure Devops Pipeline"
        response=$(curl -u :faketoken \
             -X POST \
             -H "Content-Type: application/json" \
             -d '{
                   "definition": {
                     "id": 97
                   },
                   "sourceBranch": "feature/quest_chalmers"
                 }' \
             https://dev.azure.com/firstlightgames/blashub/_apis/build/builds?api-version=6.0)
        echo "Response: $response"