name: Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - master
      - develop
      - pipeline-test
  workflow_dispatch:

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up branch-specific variables
      id: vars
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        echo "Branch name is $BRANCH_NAME"
        if [[ "$BRANCH_NAME" == "main" ]]; then
          echo "::set-output name=PIPELINE_ID::your-main-pipeline-id"
        elif [[ "$BRANCH_NAME" == "develop" ]]; then
          echo "::set-output name=PIPELINE_ID::your-develop-pipeline-id"
        elif [[ "$BRANCH_NAME" == feature/* ]]; then
          echo "::set-output name=PIPELINE_ID::your-feature-pipeline-id"
        else
          echo "::set-output name=PIPELINE_ID::unknown"
        # Echo variables for debugging purposes
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_SHA: $GITHUB_SHA"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
      shell: bash

    - name: Trigger Azure DevOps pipeline
      uses: Azure/pipelines@v1.2
      with:
        azure-devops-project-url: https://dev.azure.com/firstlightgames/blasthub
        azure-pipeline-name: first-light.flgbackend # name of the Azure pipeline to be triggered
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
