name: Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - master
      - develop
      - pipeline-test
  workflow_dispatch:

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up branch-specific variables
      id: vars
      run: |
        if [[ "${GITHUB_REF##*/}" == "master" ]]; then
          echo "::set-output name=PIPELINE_ID::your-main-pipeline-id"
        elif [[ "${GITHUB_REF##*/}" == "develop" ]]; then
          echo "::set-output name=PIPELINE_ID::your-develop-pipeline-id"
        elif [[ "${GITHUB_REF##*/}" == "pipeline-test" ]]; then
          echo "::set-output name=PIPELINE_ID::97"
        else
          echo "::set-output name=PIPELINE_ID::unknown"
        fi
      shell: bash

    - name: Trigger Azure DevOps pipeline
      uses: Azure/pipelines@v1.2
      with:
        azure-devops-project-url: https://dev.azure.com/firstlightgames/blasthub
        azure-pipeline-name: first-light.flgbackend # name of the Azure pipeline to be triggered
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
