name: Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - master
      - develop
      - pipeline-test
  workflow_dispatch:

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    
    env:
      AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      AZURE_DEVOPS_PIPELINE_SOURCE_BRANCH: ${{ vars.AZURE_DEVOPS_PIPELINE_SOURCE_BRANCH }}
      AZURE_DEVOPS_PIPELINE_DEFINITION_ID: ${{ vars.AZURE_DEVOPS_PIPELINE_DEFINITION_ID }}
      AZURE_DEVOPS_ORGANIZATION: ${{ vars.AZURE_DEVOPS_ORGANIZATION }}
      AZURE_DEVOPS_PROJECT: ${{ vars.AZURE_DEVOPS_PROJECT }}
      GIT_SHA: ${{ github.sha }}

    steps:
      - name: Trigger Azure Devops Pipeline
        shell: bash
        run: |
          echo "Triggering Azure DevOps pipeline..."
          json_payload=$(jq -n --arg pipelineBranchName "$AZURE_DEVOPS_PIPELINE_SOURCE_BRANCH" --arg version "$GIT_SHA" '{resources: {repositories: {self: {refName: $pipelineBranchName}}}}')
          echo "Payload: $json_payload"
          curl -s -u :$AZURE_DEVOPS_TOKEN \
          -X POST \
          -H "Content-Type: application/json" \
          -d "$json_payload" \
          https://dev.azure.com/$AZURE_DEVOPS_ORGANIZATION/$AZURE_DEVOPS_PROJECT/_apis/pipelines/$AZURE_DEVOPS_PIPELINE_DEFINITION_ID/runs?api-version=6.0
    
#    steps:
#    - name: Trigger Azure Devops Pipeline
#      shell: bash
#      run: |
#        echo "Triggering Azure DevOps pipeline..."
#        json_payload=$(jq -n --arg id "$AZURE_DEVOPS_PIPELINE_DEFINITION_ID" --arg pipelineSourceBranch "refs/heads/$AZURE_DEVOPS_PIPELINE_SOURCE_BRANCH" --arg branchToBuild "$GIT_SHA" '{definition: {id: $id}, sourceBranch: $pipelineSourceBranch, parameters: {branchName: $branchToBuild}}')
#        echo "Payload: $json_payload"
#        curl -s -u :$AZURE_DEVOPS_TOKEN \
#        -X POST \
#        -H "Content-Type: application/json" \
#        -d "$json_payload" \
#        https://dev.azure.com/$AZURE_DEVOPS_ORGANIZATION/$AZURE_DEVOPS_PROJECT/_apis/build/builds?api-version=6.0
       