name: Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - master
      - develop
      - pipeline-test
  workflow_dispatch:

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    
    env:
      AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      AZURE_DEVOPS_SOURCE_BRANCH: ${{ vars.AZURE_DEVOPS_SOURCE_BRANCH }}
      AZURE_DEVOPS_PIPELINE_DEFINITION_ID: ${{ vars.AZURE_DEVOPS_PIPELINE_DEFINITION_ID }}
      AZURE_DEVOPS_ORGANIZATION: ${{ vars.AZURE_DEVOPS_ORGANIZATION }}
      AZURE_DEVOPS_PROJECT: ${{ vars.AZURE_DEVOPS_PROJECT }}

  
    
    steps:
    - name: Echo generated command
      shell: bash
      run: |
        echo "Generated curl command:"
        echo "curl -u :\$AZURE_DEVOPS_TOKEN \\"
        echo "     -X POST \\"
        echo "     -H \"Content-Type: application/json\" \\"
        echo "     -d '{"
        echo "           \"definition\": {"
        echo "             \"id\": \$AZURE_DEVOPS_PIPELINE_DEFINITION_ID"
        echo "           },"
        echo "           \"sourceBranch\": \"refs/heads/\$AZURE_DEVOPS_SOURCE_BRANCH\""
        echo "         }' \\"
        echo "     https://dev.azure.com/\$AZURE_DEVOPS_ORGANIZATION/\$AZURE_DEVOPS_PROJECT/_apis/build/builds?api-version=6.0"

    - name: Trigger Azure Devops Pipeline
      shell: bash
      run: |
        echo "Triggering Azure DevOps pipeline..."
        json_payload=$(jq -n --arg id "$AZURE_DEVOPS_PIPELINE_DEFINITION_ID" --arg branch "refs/heads/$AZURE_DEVOPS_SOURCE_BRANCH" '{definition: {id: $id}, sourceBranch: $branch}')
       response=$(curl -s -u :$AZURE_DEVOPS_TOKEN \
       -X POST \
       -H "Content-Type: application/json" \
       -d "$json_payload" \
       https://dev.azure.com/$AZURE_DEVOPS_ORGANIZATION/$AZURE_DEVOPS_PROJECT/_apis/build/builds?api-version=6.0)
       echo "Response: $response"
       if echo "$response" | grep -q '"status": "queued"'; then
                                                  echo "Pipeline triggered successfully."
       else
       echo "Failed to trigger pipeline."
       exit 1
       fi